# Site settings
title: Igor Silva
email: igorsilvadeveloper@gmail.com
url: https://github.com/igorsilvadev
description: "Professional website for iOS developer Igor Samoel da Silva. Graduated from Universidade Católica de Brasilia in Computer Science. Student of Apple Developer Academy - UCB. "
keywords: "iOS Developer, iOS Apps, iOS Games, Developer, Developer Profile, iOS Personal Projects, Igor, Samoel, Silva"
skills: "iOS Developer"
meta_author: Silva Igor Samoel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 488030 #80B3FF
  primary-rgb: "71,297,12" #"128,179,255"
  secondary: 1b1c1d #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Igor Silva
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/igorsilvadev
  - title: facebook
    url: https://www.facebook.com/igorsamoelsilva
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/ios
  - title: bitbucket
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/igorsilvadev

# Postal address (add as many lines as necessary)
address:
  - line: Brasília - DF
  - line: Brazil

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
